name: Yad2Alert Runner
run-name: ${{ github.actor }} is running out Yad2Alert 🚀

on:
  schedule:
    # run every hour
    - cron: 0 * * * *
  # push:
  #  branches:
  #    - master



jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run
        run: python main.py
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_API: ${{ secrets.BOT_API }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'projects/**/*'
          push_options: '--force'